CC=gcc

suma: matrixSumA.c
	$(CC) -o suma matrixSumA.c -lpthread
	
	
sumb: matrixSumB.c
	$(CC) -o sumb matrixSumB.c -lpthread
	
sumc: matrixSumC.c
	$(CC) -o sumc matrixSumC.c -lpthread
	
pi: pi.c
	$(CC) -o pi pi.c -lpthread